[package]
name = "image-encoder"
version = "0.1.0"
authors = ["James Birtles <james.birtles@tocabot.io>"]
edition = "2018"

[dependencies]
crc = "1.8.1"
adler32 = "1.0.4"

[dev_dependencies]
scrap = "0.5.0"
